name: hello_world_vs
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.5
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0
  firebase_analytics: ^6.3.0
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.0+1
  rxdart: 0.20.0

  validators: ^2.0.0+1
  google_sign_in: ^4.5.3
  font_awesome_flutter: 8.7.0
  flutter_phoenix: "^0.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  

flutter_icons:
  android: true
  ios: true
  image_path: "icons/logo1.png"


flutter:

 
  uses-material-design: true

  
  assets:
    - assets/facebook.png
    - icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
  